apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.label.name }}
  labels:
    app: {{ .Values.label.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
    protocol: {{ .protocol }}
  {{- end }}
  selector:
    app: {{ .Values.label.name }}
