version: '3.5'

networks:
  default:
    name: SSO-NET

services: 
  keycloak: 
    image: "quay.io/keycloak/keycloak:23.0.6"
    container_name: keycloak
    ports: 
      - "18443:8443"
      - "18080:8080"
    environment: 
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak  #this configuration or above 3 combined can be used to connect to postgres
    restart: on-failure
    command: ["start-dev"]
    depends_on:
      - postgres
      
  postgres: 
    image: postgres:15.5-alpine3.19
    container_name: postgres    
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"

  openldap: 
    image: bitnami/openldap:2.5.17-debian-12-r0
    container_name: openldap    
    volumes:
      - ./openldap_data:/bitnami/openldap
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2

#add log ELK and Monitoring
