global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

label:
  name: openldap

image:
  registry: docker.io
  repository: osixia/openldap
  tag: 1.2.3
  digest: ""
  pullPolicy: IfNotPresent

service:
  name: openldap-service
  type: NodePort
  ports:
    http:
      name: openldap-http
      port: 389
      protocol: TCP

openldapConfig:
  name: openldap-service-config
  data:
    LDAP_ADMIN_USERNAME: admin
    LDAP_ORGANISATION: "HDFC Bank."
    LDAP_DOMAIN: "hdfcbank.com"
    LDAP_BASE_DN: "dc=hdfcbank,dc=com"

openldapsecret:
  name: openldap-db-secret
  data:
    ldapAdminPassword: YWRtaW5wYXNzd29yZA==
    user01password: cGFzc3dvcmQx

replicaCount: 1
container:
  name: openldap

containerPorts:
  http: 389
  https: 636

httpRelativePath: "/"
