{{- $configName := .Values.openldapConfig.name -}}
{{- $lookupConfigMap := (lookup "v1" "ConfigMap" "default" $configName) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.openldapConfig.name }}
  labels:
    app: {{ .Values.label.name }}
data:
    {{- range $k, $v := .Values.openldapConfig.data }}
      {{ $k }}: {{ $v | quote }}
    {{- range $mk, $mv := $lookupConfigMap.data }}
    {{ if eq $k $mk }}
      {{ $mk }}: {{ $mv | quote }}
    {{ end }}
    {{- end }}
    {{- end }}