apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openldapsecret.name }}
  labels:
    app: {{ .Values.label.name }}
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: {{ .Values.openldapsecret.data.ldapAdminPassword }}
  LDAP_PASSWORDS: {{ .Values.openldapsecret.data.user01password }}